name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: krother/buildozer-action@v2
        with:
          buildozer_version: stable
        env:
          # This helps fix permission errors during the build
          BUILDOZER_ALLOW_ROOT: 1
